site_name: NodeRunner
#site_url: https://your-site-url.com
theme:
  name: "material"
  palette:
    primary: "black"
    accent: "orange"
  features:
    - navigation.tabs
    - search.highlight

nav:
  - Home: index.md
  - API Documentation: reference.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition # Enables note boxes and tips
  - toc # Generates table of contents automatically
