site_name: NodeRunner
use_directory_urls: false
repo_url: https://github.com/Noah4ever/NodeRunner

theme:
  logo: "NodeRunnerLogo.png"
  name: "material"
  favicon: "NodeRunnerLogo.png"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: "black"
      accent: "orange"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "black"
      accent: "orange"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Noah4ever

nav:
  - Home: index.md
  - API Documentation: reference.md

plugins:
  - search
  - tags
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition # Enables note boxes and tips
  - toc # Generates table of contents automatically

extra_css:
  - css/style.css
